# Registro pedagógico — Lantern Hunt

Mapeia cada `LANTERN-*` à evidência em `TESTES_GUIADOS.md`.

// Caso 1 — PEDAGOGY-TEST: LANTERN-PROC-01
// Caso 2 — PEDAGOGY-TEST: LANTERN-WATER-12
// Caso 3 — PEDAGOGY-TEST: LANTERN-CAM-02
// Caso 4 — PEDAGOGY-TEST: LANTERN-OBJ-17
// Caso 5 — PEDAGOGY-TEST: LANTERN-CHK-16
// PEDAGOGY-TEST: LANTERN-AUDIO-08
// PEDAGOGY-TEST: LANTERN-FONT-13
// PEDAGOGY-TEST: LANTERN-HUD-14
// PEDAGOGY-TEST: LANTERN-PLACE-10
// PEDAGOGY-TEST: LANTERN-PROJ-05
// PEDAGOGY-TEST: LANTERN-HIT-06
// PEDAGOGY-TEST: LANTERN-AI-07
// PEDAGOGY-TEST: LANTERN-PICKUP-09
// PEDAGOGY-TEST: LANTERN-SLIME-11
// PEDAGOGY-TEST: LANTERN-TEX-02
// PEDAGOGY-TEST: LANTERN-MENU-15
// PEDAGOGY-TEST: LANTERN-NORM-03
// PEDAGOGY-TEST: LANTERN-LIGHT-04

int pedagogy_test_registry() {
    return 0;
}
