cmake_minimum_required(VERSION 3.16)
project(hid_kbd C)
enable_testing()
add_executable(hid_kbd_test hid_kbd.c test_hid_kbd.c)
target_compile_definitions(hid_kbd_test PRIVATE FIXTURES_DIR="${CMAKE_CURRENT_SOURCE_DIR}/fixtures")
if(MSVC)
  target_compile_options(hid_kbd_test PRIVATE /UNDEBUG)
endif()
add_test(NAME hid_kbd_test COMMAND hid_kbd_test)
