from __future__ import annotations

from .ast_nodes import (
    AssignStmt,
    BinaryOp,
    Call,
    Expr,
    ExprStmt,
    Function,
    IfStmt,
    LetStmt,
    Name,
    NumberLit,
    PrintStmt,
    Program,
    ReturnStmt,
    Stmt,
    UnaryOp,
    WhileStmt,
)
from .limits import DEFAULT_LIMITS, Limits


class CodegenError(ValueError):
    pass


class _Frame:
    def __init__(self, base_addr: int) -> None:
        self.base = base_addr
        self.slots: dict[str, int] = {}
        self.consts: set[str] = set()
        self.next_local = 0

    def alloc(self, name: str, *, const: bool = False) -> int:
        if name in self.slots:
            raise CodegenError(f"redeclaration of {name}")
        idx = self.next_local
        self.next_local += 1
        self.slots[name] = idx
        if const:
            self.consts.add(name)
        return self.addr(name)

    def addr(self, name: str) -> int:
        if name not in self.slots:
            raise CodegenError(f"undefined variable {name}")
        return self.base + self.slots[name] * 4

    def reset_alloc(self) -> None:
        self.slots.clear()
        self.consts.clear()
        self.next_local = 0


def _count_lets(stmts: list[Stmt]) -> int:
    n = 0
    for s in stmts:
        if isinstance(s, LetStmt):
            n += 1
        elif isinstance(s, IfStmt):
            n += _count_lets(s.then_body) + _count_lets(s.else_body)
        elif isinstance(s, WhileStmt):
            n += _count_lets(s.body)
    return n


class Codegen:
    def __init__(self, program: Program, limits: Limits = DEFAULT_LIMITS) -> None:
        self.program = program
        self.limits = limits
        self.lines: list[str] = []
        self._label_i = 0
        self.fn_names = {f.name for f in program.functions}
        self.frames: dict[str, _Frame] = {}
        self._current: _Frame | None = None

    def _label(self, prefix: str = "L") -> str:
        self._label_i += 1
        return f"_{prefix}{self._label_i}"

    def _emit(self, line: str) -> None:
        self.lines.append(line)

    def generate(self) -> str:
        names = [f.name for f in self.program.functions]
        if len(names) != len(set(names)):
            raise CodegenError("duplicate function name")

        slot_cursor = 0
        main_need = _count_lets(self.program.main)
        self.frames["__main__"] = _Frame(0)
        slot_cursor += main_need

        for fn in self.program.functions:
            if fn.name == "print":
                raise CodegenError("cannot define builtin name print")
            need = len(fn.params) + _count_lets(fn.body)
            self.frames[fn.name] = _Frame(slot_cursor * 4)
            slot_cursor += need

        if slot_cursor > self.limits.max_slots:
            raise CodegenError(
                f"too many locals: need {slot_cursor} slots, max {self.limits.max_slots} "
                f"(mem {self.limits.mem_size} B)"
            )

        self._current = self.frames["__main__"]
        self._current.reset_alloc()
        for stmt in self.program.main:
            self._stmt(stmt)
        self._emit("HALT")

        for fn in self.program.functions:
            self._emit(f"{fn.name}:")
            self._current = self.frames[fn.name]
            self._current.reset_alloc()
            for name in reversed(fn.params):
                addr = self._current.alloc(name)
                self._emit(f"PUSH {addr}")
                self._emit("STORE")
            returned = False
            for stmt in fn.body:
                if isinstance(stmt, ReturnStmt):
                    self._stmt(stmt)
                    returned = True
                    break
                self._stmt(stmt)
            if not returned:
                self._emit("PUSH 0")
                self._emit("RET")

        header = [
            "# generated by js2clvm — do not edit by hand",
            f"# slots_used={slot_cursor} max_slots={self.limits.max_slots}",
        ]
        return "\n".join(header + self.lines) + "\n"

    def _stmt(self, stmt: Stmt) -> None:
        assert self._current is not None
        if isinstance(stmt, LetStmt):
            self._expr(stmt.expr)
            addr = self._current.alloc(stmt.name, const=stmt.const)
            self._emit(f"PUSH {addr}")
            self._emit("STORE")
        elif isinstance(stmt, AssignStmt):
            if stmt.name in self._current.consts:
                raise CodegenError(f"cannot assign to const {stmt.name}")
            self._expr(stmt.expr)
            addr = self._current.addr(stmt.name)
            self._emit(f"PUSH {addr}")
            self._emit("STORE")
        elif isinstance(stmt, PrintStmt):
            self._expr(stmt.expr)
            self._emit("PRINT")
        elif isinstance(stmt, ExprStmt):
            self._expr(stmt.expr)
            self._emit("DROP")
        elif isinstance(stmt, ReturnStmt):
            self._expr(stmt.expr)
            self._emit("RET")
        elif isinstance(stmt, IfStmt):
            self._expr(stmt.cond)
            else_l = self._label("else")
            end_l = self._label("endif")
            self._emit(f"JZ {else_l}")
            for s in stmt.then_body:
                self._stmt(s)
            self._emit(f"JMP {end_l}")
            self._emit(f"{else_l}:")
            for s in stmt.else_body:
                self._stmt(s)
            self._emit(f"{end_l}:")
        elif isinstance(stmt, WhileStmt):
            head = self._label("while")
            end = self._label("wend")
            self._emit(f"{head}:")
            self._expr(stmt.cond)
            self._emit(f"JZ {end}")
            for s in stmt.body:
                self._stmt(s)
            self._emit(f"JMP {head}")
            self._emit(f"{end}:")
        else:
            raise CodegenError(f"unsupported stmt {type(stmt)}")

    def _expr(self, expr: Expr) -> None:
        assert self._current is not None
        if isinstance(expr, NumberLit):
            if not -2147483648 <= expr.value <= 2147483647:
                raise CodegenError("integer literal out of i32 range")
            self._emit(f"PUSH {expr.value}")
        elif isinstance(expr, Name):
            addr = self._current.addr(expr.ident)
            self._emit(f"PUSH {addr}")
            self._emit("LOAD")
        elif isinstance(expr, UnaryOp):
            if expr.op == "-":
                self._emit("PUSH 0")
                self._expr(expr.expr)
                self._emit("SUB")
            elif expr.op == "!":
                self._expr(expr.expr)
                self._emit("PUSH 0")
                self._emit("EQ")
            else:
                raise CodegenError(f"bad unary {expr.op}")
        elif isinstance(expr, BinaryOp):
            self._binop(expr)
        elif isinstance(expr, Call):
            if expr.callee not in self.fn_names:
                raise CodegenError(f"unknown function {expr.callee}")
            fn = next(f for f in self.program.functions if f.name == expr.callee)
            if len(expr.args) != len(fn.params):
                raise CodegenError(
                    f"{expr.callee} expects {len(fn.params)} args, got {len(expr.args)}"
                )
            for a in expr.args:
                self._expr(a)
            self._emit(f"CALL {expr.callee}")
        else:
            raise CodegenError(f"unsupported expr {type(expr)}")

    def _binop(self, expr: BinaryOp) -> None:
        op = expr.op
        if op == "%":
            # a % b => a - (a/b)*b  (no MOD opcode in CLVM v1)
            self._expr(expr.left)
            self._expr(expr.left)
            self._expr(expr.right)
            self._emit("DIV")
            self._expr(expr.right)
            self._emit("MUL")
            self._emit("SUB")
            return
        if op in ("+", "-", "*", "/"):
            self._expr(expr.left)
            self._expr(expr.right)
            self._emit({"+": "ADD", "-": "SUB", "*": "MUL", "/": "DIV"}[op])
            return
        if op == "==":
            self._expr(expr.left)
            self._expr(expr.right)
            self._emit("EQ")
            return
        if op == "!=":
            self._expr(expr.left)
            self._expr(expr.right)
            self._emit("EQ")
            self._emit("PUSH 0")
            self._emit("EQ")
            return
        if op == "<":
            self._expr(expr.left)
            self._expr(expr.right)
            self._emit("LT")
            return
        if op == ">":
            self._expr(expr.right)
            self._expr(expr.left)
            self._emit("LT")
            return
        if op == "<=":
            self._expr(expr.right)
            self._expr(expr.left)
            self._emit("LT")
            self._emit("PUSH 0")
            self._emit("EQ")
            return
        if op == ">=":
            self._expr(expr.left)
            self._expr(expr.right)
            self._emit("LT")
            self._emit("PUSH 0")
            self._emit("EQ")
            return
        raise CodegenError(f"unsupported operator {op}")


def compile_to_asm(source: str, limits: Limits = DEFAULT_LIMITS) -> str:
    from .parser import parse_source

    return Codegen(parse_source(source), limits).generate()
