# CMake generated Testfile for 
# Source directory: E:/Aulas/low-level-unified-portfolio/days/2026-09-06/graphics/portal_verlet_physics/solutions
# Build directory: E:/Aulas/low-level-unified-portfolio/days/2026-09-06/graphics/portal_verlet_physics/solutions/build_ci
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_portal_transform "E:/Aulas/low-level-unified-portfolio/days/2026-09-06/graphics/portal_verlet_physics/solutions/build_ci/Debug/test_portal_transform.exe")
  set_tests_properties(test_portal_transform PROPERTIES  _BACKTRACE_TRIPLES "E:/Aulas/low-level-unified-portfolio/days/2026-09-06/graphics/portal_verlet_physics/solutions/CMakeLists.txt;17;add_test;E:/Aulas/low-level-unified-portfolio/days/2026-09-06/graphics/portal_verlet_physics/solutions/CMakeLists.txt;20;add_portal_test;E:/Aulas/low-level-unified-portfolio/days/2026-09-06/graphics/portal_verlet_physics/solutions/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_portal_transform "E:/Aulas/low-level-unified-portfolio/days/2026-09-06/graphics/portal_verlet_physics/solutions/build_ci/Release/test_portal_transform.exe")
  set_tests_properties(test_portal_transform PROPERTIES  _BACKTRACE_TRIPLES "E:/Aulas/low-level-unified-portfolio/days/2026-09-06/graphics/portal_verlet_physics/solutions/CMakeLists.txt;17;add_test;E:/Aulas/low-level-unified-portfolio/days/2026-09-06/graphics/portal_verlet_physics/solutions/CMakeLists.txt;20;add_portal_test;E:/Aulas/low-level-unified-portfolio/days/2026-09-06/graphics/portal_verlet_physics/solutions/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_portal_transform "E:/Aulas/low-level-unified-portfolio/days/2026-09-06/graphics/portal_verlet_physics/solutions/build_ci/MinSizeRel/test_portal_transform.exe")
  set_tests_properties(test_portal_transform PROPERTIES  _BACKTRACE_TRIPLES "E:/Aulas/low-level-unified-portfolio/days/2026-09-06/graphics/portal_verlet_physics/solutions/CMakeLists.txt;17;add_test;E:/Aulas/low-level-unified-portfolio/days/2026-09-06/graphics/portal_verlet_physics/solutions/CMakeLists.txt;20;add_portal_test;E:/Aulas/low-level-unified-portfolio/days/2026-09-06/graphics/portal_verlet_physics/solutions/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_portal_transform "E:/Aulas/low-level-unified-portfolio/days/2026-09-06/graphics/portal_verlet_physics/solutions/build_ci/RelWithDebInfo/test_portal_transform.exe")
  set_tests_properties(test_portal_transform PROPERTIES  _BACKTRACE_TRIPLES "E:/Aulas/low-level-unified-portfolio/days/2026-09-06/graphics/portal_verlet_physics/solutions/CMakeLists.txt;17;add_test;E:/Aulas/low-level-unified-portfolio/days/2026-09-06/graphics/portal_verlet_physics/solutions/CMakeLists.txt;20;add_portal_test;E:/Aulas/low-level-unified-portfolio/days/2026-09-06/graphics/portal_verlet_physics/solutions/CMakeLists.txt;0;")
else()
  add_test(test_portal_transform NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_verlet_rope "E:/Aulas/low-level-unified-portfolio/days/2026-09-06/graphics/portal_verlet_physics/solutions/build_ci/Debug/test_verlet_rope.exe")
  set_tests_properties(test_verlet_rope PROPERTIES  _BACKTRACE_TRIPLES "E:/Aulas/low-level-unified-portfolio/days/2026-09-06/graphics/portal_verlet_physics/solutions/CMakeLists.txt;17;add_test;E:/Aulas/low-level-unified-portfolio/days/2026-09-06/graphics/portal_verlet_physics/solutions/CMakeLists.txt;21;add_portal_test;E:/Aulas/low-level-unified-portfolio/days/2026-09-06/graphics/portal_verlet_physics/solutions/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_verlet_rope "E:/Aulas/low-level-unified-portfolio/days/2026-09-06/graphics/portal_verlet_physics/solutions/build_ci/Release/test_verlet_rope.exe")
  set_tests_properties(test_verlet_rope PROPERTIES  _BACKTRACE_TRIPLES "E:/Aulas/low-level-unified-portfolio/days/2026-09-06/graphics/portal_verlet_physics/solutions/CMakeLists.txt;17;add_test;E:/Aulas/low-level-unified-portfolio/days/2026-09-06/graphics/portal_verlet_physics/solutions/CMakeLists.txt;21;add_portal_test;E:/Aulas/low-level-unified-portfolio/days/2026-09-06/graphics/portal_verlet_physics/solutions/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_verlet_rope "E:/Aulas/low-level-unified-portfolio/days/2026-09-06/graphics/portal_verlet_physics/solutions/build_ci/MinSizeRel/test_verlet_rope.exe")
  set_tests_properties(test_verlet_rope PROPERTIES  _BACKTRACE_TRIPLES "E:/Aulas/low-level-unified-portfolio/days/2026-09-06/graphics/portal_verlet_physics/solutions/CMakeLists.txt;17;add_test;E:/Aulas/low-level-unified-portfolio/days/2026-09-06/graphics/portal_verlet_physics/solutions/CMakeLists.txt;21;add_portal_test;E:/Aulas/low-level-unified-portfolio/days/2026-09-06/graphics/portal_verlet_physics/solutions/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_verlet_rope "E:/Aulas/low-level-unified-portfolio/days/2026-09-06/graphics/portal_verlet_physics/solutions/build_ci/RelWithDebInfo/test_verlet_rope.exe")
  set_tests_properties(test_verlet_rope PROPERTIES  _BACKTRACE_TRIPLES "E:/Aulas/low-level-unified-portfolio/days/2026-09-06/graphics/portal_verlet_physics/solutions/CMakeLists.txt;17;add_test;E:/Aulas/low-level-unified-portfolio/days/2026-09-06/graphics/portal_verlet_physics/solutions/CMakeLists.txt;21;add_portal_test;E:/Aulas/low-level-unified-portfolio/days/2026-09-06/graphics/portal_verlet_physics/solutions/CMakeLists.txt;0;")
else()
  add_test(test_verlet_rope NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_sphere_portal "E:/Aulas/low-level-unified-portfolio/days/2026-09-06/graphics/portal_verlet_physics/solutions/build_ci/Debug/test_sphere_portal.exe")
  set_tests_properties(test_sphere_portal PROPERTIES  _BACKTRACE_TRIPLES "E:/Aulas/low-level-unified-portfolio/days/2026-09-06/graphics/portal_verlet_physics/solutions/CMakeLists.txt;17;add_test;E:/Aulas/low-level-unified-portfolio/days/2026-09-06/graphics/portal_verlet_physics/solutions/CMakeLists.txt;22;add_portal_test;E:/Aulas/low-level-unified-portfolio/days/2026-09-06/graphics/portal_verlet_physics/solutions/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_sphere_portal "E:/Aulas/low-level-unified-portfolio/days/2026-09-06/graphics/portal_verlet_physics/solutions/build_ci/Release/test_sphere_portal.exe")
  set_tests_properties(test_sphere_portal PROPERTIES  _BACKTRACE_TRIPLES "E:/Aulas/low-level-unified-portfolio/days/2026-09-06/graphics/portal_verlet_physics/solutions/CMakeLists.txt;17;add_test;E:/Aulas/low-level-unified-portfolio/days/2026-09-06/graphics/portal_verlet_physics/solutions/CMakeLists.txt;22;add_portal_test;E:/Aulas/low-level-unified-portfolio/days/2026-09-06/graphics/portal_verlet_physics/solutions/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_sphere_portal "E:/Aulas/low-level-unified-portfolio/days/2026-09-06/graphics/portal_verlet_physics/solutions/build_ci/MinSizeRel/test_sphere_portal.exe")
  set_tests_properties(test_sphere_portal PROPERTIES  _BACKTRACE_TRIPLES "E:/Aulas/low-level-unified-portfolio/days/2026-09-06/graphics/portal_verlet_physics/solutions/CMakeLists.txt;17;add_test;E:/Aulas/low-level-unified-portfolio/days/2026-09-06/graphics/portal_verlet_physics/solutions/CMakeLists.txt;22;add_portal_test;E:/Aulas/low-level-unified-portfolio/days/2026-09-06/graphics/portal_verlet_physics/solutions/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_sphere_portal "E:/Aulas/low-level-unified-portfolio/days/2026-09-06/graphics/portal_verlet_physics/solutions/build_ci/RelWithDebInfo/test_sphere_portal.exe")
  set_tests_properties(test_sphere_portal PROPERTIES  _BACKTRACE_TRIPLES "E:/Aulas/low-level-unified-portfolio/days/2026-09-06/graphics/portal_verlet_physics/solutions/CMakeLists.txt;17;add_test;E:/Aulas/low-level-unified-portfolio/days/2026-09-06/graphics/portal_verlet_physics/solutions/CMakeLists.txt;22;add_portal_test;E:/Aulas/low-level-unified-portfolio/days/2026-09-06/graphics/portal_verlet_physics/solutions/CMakeLists.txt;0;")
else()
  add_test(test_sphere_portal NOT_AVAILABLE)
endif()
