"""Map day modules to cumulative projects/ for porting guide."""
from __future__ import annotations

MODULE_PROJECT: dict[str, dict[str, str]] = {
    # Day 01
    "2026-09-03/ai/linear_autograd": {
        "project": "projects/chris-autograd",
        "carry": "gradient ops + training loop (not lab harness)",
        "tests": "gradient/regression tests in project",
        "milestone": "MILESTONES.md — scalar autograd",
        "commit": "feat(autograd): port linear training from day01 lab",
    },
    "2026-09-03/architecture/toy_cpu": {
        "project": "projects/chris-cpu",
        "carry": "fetch/decode/execute core",
        "tests": "unit tests for opcode semantics",
        "milestone": "MILESTONES.md — instruction subset",
        "commit": "feat(cpu): port toy CPU from day01 lab",
    },
    "2026-09-03/assembly/x86_64_abi_sum": {
        "project": "projects/chris-assembly-lab",
        "carry": "System V sum function in assembly",
        "tests": "ABI boundary tests",
        "milestone": "MILESTONES.md — ABI lab",
        "commit": "feat(asm): port x86-64 sum from day01 lab",
    },
    "2026-09-03/blockchain/toy_chain": {
        "project": "projects/chris-chain",
        "carry": "block hash + chain validation",
        "tests": "tamper/PoW tests",
        "milestone": "MILESTONES.md — hash chain",
        "commit": "feat(chain): port toy chain from day01 lab",
    },
    "2026-09-03/boot/legacy_bootsector": {
        "project": "projects/chris-boot",
        "carry": "512-byte boot sector layout",
        "tests": "binary layout tests",
        "milestone": "MILESTONES.md — boot sector",
        "commit": "feat(boot): port legacy bootsector from day01 lab",
    },
    "2026-09-03/graphics/dual_backend_3d": {
        "project": "projects/chris-renderer",
        "carry": "shared 3D core + backend interface",
        "tests": "software vs GL parity tests",
        "milestone": "MILESTONES.md — dual backend",
        "commit": "feat(renderer): port 3D core from day01 lab",
    },
    "2026-09-03/hardware/descriptor_ring": {
        "project": "projects/chris-driver-lab",
        "carry": "descriptor ring submit/complete",
        "tests": "wrap/full/order tests",
        "milestone": "MILESTONES.md — NIC ring sim",
        "commit": "feat(driver): port descriptor ring from day01 lab",
    },
    "2026-09-03/network/http_parser": {
        "project": "projects/chris-http",
        "carry": "incremental HTTP/1.x parser",
        "tests": "fragmentation + negative cases",
        "milestone": "MILESTONES.md — HTTP parser",
        "commit": "feat(http): port incremental parser from day01 lab",
    },
    "2026-09-03/p2p/gossip": {
        "project": "projects/chris-p2p",
        "carry": "gossip dedup + TTL broadcast",
        "tests": "topology/property tests",
        "milestone": "MILESTONES.md — gossip sim",
        "commit": "feat(p2p): port gossip from day01 lab",
    },
    "2026-09-03/redteam/benign_reversing": {
        "project": "projects/chris-binary-toolkit",
        "carry": "strings/YARA-style scanning",
        "tests": "unit tests on fixtures",
        "milestone": "MILESTONES.md — binary toolkit",
        "commit": "feat(toolkit): port reversing helpers from day01 lab",
    },
    "2026-09-03/systems/clvm": {
        "project": "projects/chris-vm",
        "carry": "CLVM loader + stack VM",
        "tests": "integration tests",
        "milestone": "MILESTONES.md — CLVM VM",
        "commit": "feat(vm): port CLVM from day01 lab",
    },
    "2026-09-04/systems/clvm_extended": {
        "project": "projects/chris-vm",
        "carry": "CALL/RET, LOAD/STORE, EQ/LT/JNZ/SWAP/DROP",
        "tests": "add2 + mem_demo + max_loop + negatives",
        "milestone": "MILESTONES.md — Day 04 extended ISA",
        "commit": "feat(vm): extended ISA from day04 clvm_extended",
    },
    "2026-09-07/systems/clvm_js_codegen": {
        "project": "projects/chris-vm",
        "carry": "js2clvm codegen (LET/WHILE/CALL)",
        "tests": "integration_test.py goldens",
        "milestone": "MILESTONES.md — N1 codegen lab",
        "commit": "feat(vm): port js codegen from day07",
    },
    "2026-09-07/systems/clvm_bytecode_verifier": {
        "project": "projects/chris-vm",
        "carry": "verify_clvm stack-effect + branches",
        "tests": "fixtures ok/bad_checksum",
        "milestone": "MILESTONES.md — N2 verifier lab",
        "commit": "feat(vm): port verifier from day07",
    },
    "2026-09-07/systems/clvm_v2_strings": {
        "project": "projects/chris-vm",
        "carry": "FORMAT v2 string pool + PRINTS (experimental)",
        "tests": "hello hi",
        "milestone": "MILESTONES.md — N4 v2 strings",
        "commit": "feat(vm): explore CLVM v2 strings from day07",
    },
    "2026-09-07/linux/hid_keyboard_boot": {
        "project": "projects/chris-driver-lab",
        "carry": "HID boot keyboard decode + input ring",
        "tests": "hid_kbd_test ctest",
        "milestone": "MILESTONES.md — HID input queue",
        "commit": "feat(driver-lab): port hid keyboard boot from day07",
    },
    "2026-09-07/linux/ps2_mouse_input": {
        "project": "projects/chris-driver-lab",
        "carry": "PS/2 mouse packet → relative events",
        "tests": "ps2_mouse_test ctest",
        "milestone": "MILESTONES.md — PS/2 input",
        "commit": "feat(driver-lab): port ps2 mouse from day07",
    },
    "2026-09-07/rust/clvm_v2_verify": {
        "project": "projects/chris-vm",
        "carry": "Rust CLVM v2 parser + stack verify",
        "tests": "cargo test clvm_v2",
        "milestone": "MILESTONES.md — rust verifier v2",
        "commit": "feat(vm): rust clvm v2 verifier from day07",
    },
    "2026-09-07/dotnet/input_event_span": {
        "project": "projects/chris-dotnet-bench",
        "carry": "evdev InputEvent + Span HID/PS2 parsers",
        "tests": "dotnet test InputLab",
        "milestone": "MILESTONES.md — input span parsers",
        "commit": "feat(dotnet-bench): port input event span from day07",
    },
    "2026-09-03/terminal/ansi_parser": {
        "project": "projects/chris-terminal",
        "carry": "ECMA-48/ANSI state machine",
        "tests": "golden/state tests",
        "milestone": "MILESTONES.md — terminal parser",
        "commit": "feat(terminal): port ANSI parser from day01 lab",
    },
    "2026-09-03/tooling/miniobjdump": {
        "project": "projects/chris-disassembler",
        "carry": "ELF/PE inspection + decode subset",
        "tests": "integration tests",
        "milestone": "MILESTONES.md — disassembler",
        "commit": "feat(disasm): port miniobjdump from day01 lab",
    },
    # Day 02
    "2026-09-04/systems/arena_allocator": {
        "project": "projects/chris-arena",
        "carry": "Arena allocate/reset/align",
        "tests": "arena unit tests",
        "milestone": "MILESTONES.md — arena allocator",
        "commit": "feat(arena): port allocator from day02 lab",
    },
    "2026-09-04/ai/tensor_strides": {
        "project": "projects/chris-tensor",
        "carry": "strided tensor views + matmul",
        "tests": "tensor shape tests",
        "milestone": "MILESTONES.md — tensor core",
        "commit": "feat(tensor): port strides from day02 lab",
    },
    "2026-09-04/algorithms/blocked_merge_sort": {
        "project": "projects/chris-algorithms",
        "carry": "blocked merge sort + SortIoStats",
        "tests": "correctness + tile I/O accounting",
        "milestone": "MILESTONES.md — blocked merge sort",
        "commit": "feat(algo): port blocked merge sort from day02 lab",
    },
    "2026-09-04/quantum/statevector_intro": {
        "project": "projects/chris-qsim",
        "carry": "statevector gates",
        "tests": "gate unit tests",
        "milestone": "MILESTONES.md — qsim intro",
        "commit": "feat(qsim): port statevector from day02 lab",
    },
    "2026-09-04/os/graphics_reference": {
        "project": "projects/chris-os",
        "carry": "software compositor",
        "tests": "pixel compositing tests",
        "milestone": "MILESTONES.md — OS graphics ref",
        "commit": "feat(os): port compositor from day02 lab",
    },
    "2026-09-04/debugger/protocol_v1": {
        "project": "projects/chris-debugger",
        "carry": "debugger wire protocol v1",
        "tests": "encode/decode roundtrip",
        "milestone": "MILESTONES.md — protocol v1",
        "commit": "feat(debugger): port protocol from day02 lab",
    },
    "2026-09-04/redteam/elf64_triage": {
        "project": "projects/chris-binary-toolkit",
        "carry": "ELF64 header triage",
        "tests": "elf64_benchmark.py",
        "milestone": "MILESTONES.md — ELF triage",
        "commit": "feat(toolkit): port elf64 triage from day02 lab",
    },
    "2026-09-04/dotnet/csharp_span_arraypool": {
        "project": "projects/chris-dotnet-bench",
        "carry": "Span/ArrayPool patterns",
        "tests": "dotnet benchmarks",
        "milestone": "MILESTONES.md — .NET buffers",
        "commit": "feat(dotnet): port span lab from day02",
    },
    "2026-09-04/dotnet/clr_pe_cli_metadata": {
        "project": "projects/chris-dotnet-pe",
        "carry": "PE/CLI metadata reader",
        "tests": "PE fixture tests",
        "milestone": "MILESTONES.md — PE reader",
        "commit": "feat(pe): port CLR metadata from day02 lab",
    },
    "2026-09-04/nodejs/typescript_stream_backpressure": {
        "project": "projects/chris-node-streaming",
        "carry": "Transform stream + backpressure",
        "tests": "stream unit tests",
        "milestone": "MILESTONES.md — Node streams",
        "commit": "feat(node): port TS streams from day02 lab",
    },
    "2026-09-04/javascript/bytecode_vm_from_scratch": {
        "project": "projects/chris-js",
        "carry": "bytecode VM core",
        "tests": "vm test.js",
        "milestone": "MILESTONES.md — JS VM",
        "commit": "feat(js): port bytecode VM from day02 lab",
    },
    # Day 05
    "2026-09-05/ai/tiled_matmul_cache": {
        "project": "projects/chris-tensor/day03_tiled_matmul",
        "carry": "tiled matmul + bench",
        "tests": "matmul correctness tests",
        "milestone": "day03 tiled matmul milestone",
        "commit": "feat(tensor): port tiled matmul from day05 lab",
    },
    "2026-09-05/dotnet/cil_tiny_decoder": {
        "project": "projects/chris-dotnet-ilvm/day03",
        "carry": "CIL opcode decoder",
        "tests": "dotnet run on fixtures",
        "milestone": "IL decoder milestone",
        "commit": "feat(ilvm): port CIL decoder from day05 lab",
    },
    "2026-09-05/graphics/vulkan_d3d12_resource_states": {
        "project": "projects/chris-gpu-state/day03",
        "carry": "resource state machine + frame graph",
        "tests": "state transition tests",
        "milestone": "GPU state sim milestone",
        "commit": "feat(gpu): port resource states from day05 lab",
    },
    "2026-09-05/javascript/bytecode_branch_vm": {
        "project": "projects/chris-js/day03_branches",
        "carry": "branching bytecode VM",
        "tests": "vm branch tests",
        "milestone": "JS branch VM milestone",
        "commit": "feat(js): port branch VM from day05 lab",
    },
    "2026-09-05/linux/distro_pkg_rootfs": {
        "project": "projects/chris-linux-pkg/day03",
        "carry": "pkg parser + rootfs builder",
        "tests": "test_pkg.py + test_rootfs.sh",
        "milestone": "linux pkg milestone",
        "commit": "feat(linux): port pkg/rootfs from day05 lab",
    },
    "2026-09-05/linux/kernel_module_driver_lab": {
        "project": "projects/chris-linux-module-lab/day03",
        "carry": "device_model userspace + review notes",
        "tests": "test_device_model",
        "milestone": "kmod lab milestone",
        "commit": "feat(kmod): port device model from day05 lab",
    },
    "2026-09-05/linux/pty_ansi_terminal": {
        "project": "projects/chris-linux-terminal/day03_ansi",
        "carry": "ANSI parser for terminal",
        "tests": "test_ansi.py",
        "milestone": "linux terminal milestone",
        "commit": "feat(terminal): port ANSI parser from day05 lab",
    },
    "2026-09-05/nodejs/stream_transform_backpressure": {
        "project": "projects/chris-node-streaming/day03_backpressure",
        "carry": "backpressure demo + transform",
        "tests": "test.js",
        "milestone": "backpressure milestone",
        "commit": "feat(node): port backpressure from day05 lab",
    },
    "2026-09-05/redteam/elf_entry_inspector": {
        "project": "projects/chris-binary-toolkit",
        "carry": "ELF64 entry-point parser",
        "tests": "elf_entry tests",
        "milestone": "ELF entry milestone",
        "commit": "feat(toolkit): port elf entry from day05 lab",
    },
    "2026-09-05/systems/bitmap_page_allocator": {
        "project": "projects/chris-pagealloc/day03",
        "carry": "bitmap page allocator",
        "tests": "page allocator tests",
        "milestone": "pagealloc milestone",
        "commit": "feat(pagealloc): port bitmap allocator from day05 lab",
    },
    "2026-09-07/graphics/artillery_trajectory_2d": {
        "project": "projects/chris-artillery-2d",
        "carry": "2D projectile physics + triple backend",
        "tests": "test_artillery + visual parity",
        "milestone": "artillery 2D milestone",
        "commit": "feat(gfx): port artillery trajectory from day07 lab",
    },
    "2026-09-07/graphics/raster_depth_parity": {
        "project": "projects/chris-renderer/day07-depth",
        "carry": "CPU depth buffer + GL parity",
        "tests": "test_depth",
        "milestone": "depth parity milestone",
        "commit": "feat(renderer): port depth parity from day07 lab",
    },
    "2026-09-07/redteam/hid_report_fuzz": {
        "project": "projects/chris-binary-toolkit",
        "carry": "HID boot report validation + fuzz bounds",
        "tests": "pytest test_hid_fuzz",
        "milestone": "MILESTONES.md — HID fuzz triage",
        "commit": "feat(toolkit): port hid report fuzz from day07",
    },
    "2026-09-07/quantum/measurement_born": {
        "project": "projects/chris-qsim",
        "carry": "Born rule measurement + collapse on 2-qubit statevector",
        "tests": "ctest measure_tests",
        "milestone": "MILESTONES.md — measurement Born lab",
        "commit": "feat(qsim): port measurement born from day07",
    },
    "2026-09-07/ai/input_event_entropy": {
        "project": "projects/chris-tensor",
        "carry": "Shannon + RLE + gzip ratio on InputEvent bytes",
        "tests": "pytest test_input_entropy",
        "milestone": "MILESTONES.md — input event entropy",
        "commit": "feat(tensor): port input event entropy from day07",
    },
    "2026-09-07/nodejs/input_event_transform": {
        "project": "projects/chris-node-streaming",
        "carry": "ESM Transform parsing 24-byte InputEvent records",
        "tests": "node test.js",
        "milestone": "MILESTONES.md — input event transform",
        "commit": "feat(node): port input event transform from day07",
    },
    "2026-09-07/ai/kv_cache_ring": {
        "project": "projects/chris-tensor",
        "carry": "KV cache ring buffer + eviction tags",
        "tests": "pytest test_kv_cache",
        "milestone": "MILESTONES.md — kv cache ring",
        "commit": "feat(tensor): port kv cache ring from day07",
    },
    "2026-09-07/redteam/elf_program_header_triage": {
        "project": "projects/chris-binary-toolkit",
        "carry": "ELF64 PHDR parse + range validation",
        "tests": "pytest test_elf_phdr",
        "milestone": "MILESTONES.md — elf phdr triage",
        "commit": "feat(toolkit): port elf phdr triage from day07",
    },
    "2026-09-07/dotnet/cil_cfg_verifier": {
        "project": "projects/chris-dotnet-bench",
        "carry": "CIL CFG stack depth worklist",
        "tests": "dotnet test Chris.CilCfg.Tests",
        "milestone": "MILESTONES.md — cil cfg verifier",
        "commit": "feat(dotnet-bench): port cil cfg from day07",
    },
    "2026-09-07/nodejs/libuv_phase_probe": {
        "project": "projects/chris-node-streaming",
        "carry": "libuv phase ordering probes",
        "tests": "node test.js",
        "milestone": "MILESTONES.md — libuv phase probe",
        "commit": "feat(node): port libuv probe from day07",
    },
    "2026-09-07/graphics/resource_state_tracker": {
        "project": "projects/chris-gpu-state",
        "carry": "resource state barrier batching",
        "tests": "ctest state_tracker",
        "milestone": "MILESTONES.md — resource state tracker",
        "commit": "feat(gpu-state): port state tracker from day07",
    },
    "2026-09-07/linux/proc_task_snapshot": {
        "project": "projects/chris-top",
        "carry": "/proc stat parse + PID reuse guard",
        "tests": "pytest test_proc_snapshot",
        "milestone": "MILESTONES.md — proc snapshot",
        "commit": "feat(top): port proc snapshot from day07",
    },
    "2026-09-07/parsers/pratt_query_lang": {
        "project": "projects/chris-smart-grep",
        "carry": "Pratt parser for query language",
        "tests": "pytest test_query",
        "milestone": "MILESTONES.md — pratt query lang",
        "commit": "feat(grep): port pratt query from day07",
    },
    "2026-09-07/agent/loop_state_machine": {
        "project": "projects/chris-agent-harness",
        "carry": "perceive→verify FSM + deterministic replay",
        "tests": "pytest test_agent_fsm",
        "milestone": "MILESTONES.md — agent loop fsm",
        "commit": "feat(agent): port loop fsm from day07",
    },
    "2026-09-08/systems/clvm_disassembler": {
        "project": "projects/chris-vm",
        "carry": "CLVM v2 disassembler text output",
        "tests": "python test_clvm_disassembler",
        "milestone": "MILESTONES.md — clvm disassembler",
        "commit": "feat(vm): port clvm disassembler from day08",
    },
    "2026-09-08/systems/clvm_peephole_opt": {
        "project": "projects/chris-vm",
        "carry": "peephole constant fold on bytecode",
        "tests": "python test_clvm_peephole_opt",
        "milestone": "MILESTONES.md — clvm peephole",
        "commit": "feat(vm): port clvm peephole from day08",
    },
    "2026-09-08/linux/input_event_ring_mux": {
        "project": "projects/chris-driver-lab",
        "carry": "input event ring mux kbd+mouse",
        "tests": "python test_input_event_ring_mux",
        "milestone": "MILESTONES.md — input ring mux",
        "commit": "feat(driver-lab): port input ring mux from day08",
    },
    "2026-09-08/rust/clvm_disasm": {
        "project": "projects/chris-vm",
        "carry": "Rust CLVM disassembler",
        "tests": "cargo test clvm_disasm",
        "milestone": "MILESTONES.md — rust clvm disasm",
        "commit": "feat(vm): port rust clvm disasm from day08",
    },
    "2026-09-08/dotnet/pe_export_span": {
        "project": "projects/chris-binary-toolkit",
        "carry": "PE export parse with Span",
        "tests": "dotnet test PeExport",
        "milestone": "MILESTONES.md — pe export span",
        "commit": "feat(toolkit): port pe export span from day08",
    },
    "2026-09-08/graphics/shader_stage_fsm": {
        "project": "projects/chris-renderer",
        "carry": "shader compile stage FSM sim",
        "tests": "python test_shader_stage_fsm",
        "milestone": "MILESTONES.md — shader stage fsm",
        "commit": "feat(renderer): port shader fsm from day08",
    },
    "2026-09-08/redteam/pe_export_triage": {
        "project": "projects/chris-binary-toolkit",
        "carry": "PE export IOC triage",
        "tests": "python test_pe_export_triage",
        "milestone": "MILESTONES.md — pe export triage",
        "commit": "feat(toolkit): port pe export triage from day08",
    },
    "2026-09-08/quantum/bell_state_prep": {
        "project": "projects/chris-qsim",
        "carry": "Bell state |00>+|11> prep",
        "tests": "python test_bell_state_prep",
        "milestone": "MILESTONES.md — bell state prep",
        "commit": "feat(qsim): port bell state from day08",
    },
    "2026-09-08/ai/softmax_stable": {
        "project": "projects/chris-autograd",
        "carry": "stable softmax / log-softmax / CE",
        "tests": "python test_softmax_stable",
        "milestone": "MILESTONES.md — softmax stable",
        "commit": "feat(autograd): port softmax stable from day08",
    },
    "2026-09-08/nodejs/duplex_event_pipe": {
        "project": "projects/chris-driver-lab",
        "carry": "Duplex 24B event pipe",
        "tests": "node test.js",
        "milestone": "MILESTONES.md — duplex event pipe",
        "commit": "feat(driver-lab): port duplex pipe from day08",
    },
    "2026-09-08/parsers/json_rd_lexer": {
        "project": "projects/chris-smart-grep",
        "carry": "JSON subset lexer + RD",
        "tests": "python test_json_rd_lexer",
        "milestone": "MILESTONES.md — json rd lexer",
        "commit": "feat(grep): port json lexer from day08",
    },
    "2026-09-08/agent/tool_protocol_fsm": {
        "project": "projects/chris-agent-harness",
        "carry": "tool protocol FSM",
        "tests": "python test_tool_protocol_fsm",
        "milestone": "MILESTONES.md — tool protocol fsm",
        "commit": "feat(agent): port tool fsm from day08",
    },
    "2026-09-08/tooling/wasm_section_header": {
        "project": "projects/chris-binary-toolkit",
        "carry": "WASM magic + section headers",
        "tests": "python test_wasm_section_header",
        "milestone": "MILESTONES.md — wasm section header",
        "commit": "feat(toolkit): port wasm headers from day08",
    },
    "2026-09-09/systems/clvm_trace_profiler": {
        "project": "projects/chris-vm",
        "carry": "opcode trace + hotspot counting",
        "tests": "python test_clvm_trace",
        "milestone": "MILESTONES.md — clvm trace profiler",
        "commit": "feat(vm): port clvm trace profiler from day09",
    },
    "2026-09-09/systems/arena_telemetry": {
        "project": "projects/chris-vm",
        "carry": "bump arena stats/telemetry",
        "tests": "python test_arena",
        "milestone": "MILESTONES.md — arena telemetry",
        "commit": "feat(vm): port arena telemetry from day09",
    },
    "2026-09-09/linux/perf_event_open_lab": {
        "project": "projects/chris-top",
        "carry": "perf_event syscall subset simulation",
        "tests": "python test_perf_lab",
        "milestone": "MILESTONES.md — perf event lab",
        "commit": "feat(top): port perf event lab from day09",
    },
    "2026-09-09/rust/stack_sample_trace": {
        "project": "projects/chris-compress",
        "carry": "Rust stack sampling trace",
        "tests": "cargo test stack",
        "milestone": "MILESTONES.md — stack sample trace",
        "commit": "feat(compress): port stack trace from day09",
    },
    "2026-09-09/dotnet/activity_source_span": {
        "project": "projects/chris-dotnet-bench",
        "carry": "ActivitySource diagnostic spans",
        "tests": "dotnet test ActivityLab",
        "milestone": "MILESTONES.md — activity source span",
        "commit": "feat(dotnet-bench): port activity source from day09",
    },
    "2026-09-09/graphics/gpu_timer_query": {
        "project": "projects/chris-artillery-2d",
        "carry": "GPU timer query simulation",
        "tests": "python test_gpu_timer",
        "milestone": "MILESTONES.md — gpu timer query",
        "commit": "feat(artillery): port gpu timer from day09",
    },
    "2026-09-09/redteam/yara_match_scan": {
        "project": "projects/chris-binary-toolkit",
        "carry": "YARA-style pattern scan",
        "tests": "python test_yara_scan",
        "milestone": "MILESTONES.md — yara match scan",
        "commit": "feat(toolkit): port yara scan from day09",
    },
    "2026-09-09/quantum/decoherence_noise": {
        "project": "projects/chris-qsim",
        "carry": "simple decoherence noise channel",
        "tests": "python test_decoherence",
        "milestone": "MILESTONES.md — decoherence noise",
        "commit": "feat(qsim): port decoherence from day09",
    },
    "2026-09-09/ai/attention_mask": {
        "project": "projects/chris-smart-grep",
        "carry": "attention mask computation",
        "tests": "python test_attention_mask",
        "milestone": "MILESTONES.md — attention mask",
        "commit": "feat(grep): port attention mask from day09",
    },
    "2026-09-09/nodejs/async_hooks_trace": {
        "project": "projects/chris-driver-lab",
        "carry": "async_hooks timeline",
        "tests": "node test.js",
        "milestone": "MILESTONES.md — async hooks trace",
        "commit": "feat(driver-lab): port async hooks from day09",
    },
    "2026-09-09/parsers/logfmt_lexer": {
        "project": "projects/chris-smart-grep",
        "carry": "logfmt key=value lexer",
        "tests": "python test_logfmt",
        "milestone": "MILESTONES.md — logfmt lexer",
        "commit": "feat(grep): port logfmt lexer from day09",
    },
    "2026-09-09/agent/verify_replay_log": {
        "project": "projects/chris-agent-harness",
        "carry": "verify+replay log FSM",
        "tests": "python test_agent_log",
        "milestone": "MILESTONES.md — verify replay log",
        "commit": "feat(agent): port verify replay log from day09",
    },
    "2026-09-09/tooling/pdb_symbol_index": {
        "project": "projects/chris-binary-toolkit",
        "carry": "PDB symbol index basics",
        "tests": "python test_pdb_index",
        "milestone": "MILESTONES.md — pdb symbol index",
        "commit": "feat(toolkit): port pdb index from day09",
    },
    "2026-09-06/redteam/compressed_blob_triage": {
        "project": "projects/chris-binary-toolkit",
        "carry": "compressed blob magic + bounds triage",
        "tests": "pytest compressed_blob",
        "milestone": "MILESTONES.md — compressed blob triage",
        "commit": "feat(toolkit): port compressed blob triage from day06",
    },
    "2026-09-06/dotnet/span_deflate_buffers": {
        "project": "projects/chris-dotnet-bench",
        "carry": "Span + deflate stored inflate",
        "tests": "dotnet test SpanDeflate",
        "milestone": "MILESTONES.md — span deflate",
        "commit": "feat(dotnet-bench): port span deflate from day06",
    },
    "2026-09-06/rust/rle_byte_codec": {
        "project": "projects/chris-compress",
        "carry": "CHRLE Rust ownership",
        "tests": "cargo test rle",
        "milestone": "MILESTONES.md — rust rle",
        "commit": "feat(compress): port rust rle from day06",
    },
    "2026-09-06/rust/gzip_member_parse": {
        "project": "projects/chris-compress",
        "carry": "gzip member header/trailer parse",
        "tests": "cargo test gzip_member",
        "milestone": "MILESTONES.md — gzip member parse",
        "commit": "feat(compress): port gzip member from day06",
    },
    "2026-09-10/systems/clvm_pipeline_integration": {
        "project": "projects/chris-vm",
        "carry": "capstone clvm_pipeline_integration from day10",
        "tests": "day10 module tests",
        "milestone": "MILESTONES.md — day10 clvm_pipeline_integration",
        "commit": "feat(day10): port clvm_pipeline_integration",
    },
    "2026-09-10/systems/unified_input_pipeline": {
        "project": "projects/chris-driver-lab",
        "carry": "capstone unified_input_pipeline from day10",
        "tests": "day10 module tests",
        "milestone": "MILESTONES.md — day10 unified_input_pipeline",
        "commit": "feat(day10): port unified_input_pipeline",
    },
    "2026-09-10/linux/composite_input_driver": {
        "project": "projects/chris-driver-lab",
        "carry": "capstone composite_input_driver from day10",
        "tests": "day10 module tests",
        "milestone": "MILESTONES.md — day10 composite_input_driver",
        "commit": "feat(day10): port composite_input_driver",
    },
    "2026-09-10/rust/cross_verify_clvm": {
        "project": "projects/chris-vm",
        "carry": "capstone cross_verify_clvm from day10",
        "tests": "day10 module tests",
        "milestone": "MILESTONES.md — day10 cross_verify_clvm",
        "commit": "feat(day10): port cross_verify_clvm",
    },
    "2026-09-10/dotnet/capstone_input_host": {
        "project": "projects/chris-driver-lab",
        "carry": "capstone capstone_input_host from day10",
        "tests": "day10 module tests",
        "milestone": "MILESTONES.md — day10 capstone_input_host",
        "commit": "feat(day10): port capstone_input_host",
    },
    "2026-09-10/graphics/pipeline_state_object": {
        "project": "projects/chris-renderer",
        "carry": "capstone pipeline_state_object from day10",
        "tests": "day10 module tests",
        "milestone": "MILESTONES.md — day10 pipeline_state_object",
        "commit": "feat(day10): port pipeline_state_object",
    },
    "2026-09-10/redteam/capstone_triage": {
        "project": "projects/chris-binary-toolkit",
        "carry": "capstone capstone_triage from day10",
        "tests": "day10 module tests",
        "milestone": "MILESTONES.md — day10 capstone_triage",
        "commit": "feat(day10): port capstone_triage",
    },
    "2026-09-10/quantum/capstone_measurement": {
        "project": "projects/chris-quantum-sim",
        "carry": "capstone capstone_measurement from day10",
        "tests": "day10 module tests",
        "milestone": "MILESTONES.md — day10 capstone_measurement",
        "commit": "feat(day10): port capstone_measurement",
    },
    "2026-09-10/ai/capstone_tokenizer": {
        "project": "projects/chris-autograd",
        "carry": "capstone capstone_tokenizer from day10",
        "tests": "day10 module tests",
        "milestone": "MILESTONES.md — day10 capstone_tokenizer",
        "commit": "feat(day10): port capstone_tokenizer",
    },
    "2026-09-10/nodejs/capstone_stream_pipeline": {
        "project": "projects/chris-http",
        "carry": "capstone capstone_stream_pipeline from day10",
        "tests": "day10 module tests",
        "milestone": "MILESTONES.md — day10 capstone_stream_pipeline",
        "commit": "feat(day10): port capstone_stream_pipeline",
    },
    "2026-09-10/parsers/capstone_query_eval": {
        "project": "projects/chris-smart-grep",
        "carry": "capstone capstone_query_eval from day10",
        "tests": "day10 module tests",
        "milestone": "MILESTONES.md — day10 capstone_query_eval",
        "commit": "feat(day10): port capstone_query_eval",
    },
    "2026-09-10/agent/capstone_agent_loop": {
        "project": "projects/chris-agent-harness",
        "carry": "capstone capstone_agent_loop from day10",
        "tests": "day10 module tests",
        "milestone": "MILESTONES.md — day10 capstone_agent_loop",
        "commit": "feat(day10): port capstone_agent_loop",
    },
    "2026-09-10/tooling/capstone_format_detect": {
        "project": "projects/chris-binary-toolkit",
        "carry": "capstone capstone_format_detect from day10",
        "tests": "day10 module tests",
        "milestone": "MILESTONES.md — day10 capstone_format_detect",
        "commit": "feat(day10): port capstone_format_detect",
    },
    "2026-09-11/systems/clvm_reloc_apply": {
        "project": "projects/chris-vm",
        "carry": "CLVM reloc apply",
        "tests": "reloc unit tests",
        "milestone": "MILESTONES.md — reloc",
        "commit": "feat(vm): port reloc apply from day11",
    },
    "2026-09-11/systems/bump_poison_arena": {
        "project": "projects/chris-arena",
        "carry": "bump poison canary",
        "tests": "arena tests",
        "milestone": "MILESTONES.md — bump",
        "commit": "feat(arena): port bump from day11",
    },
    "2026-09-11/linux/uevent_kv_parse": {
        "project": "projects/chris-driver-lab",
        "carry": "uevent kv parse",
        "tests": "uevent tests",
        "milestone": "MILESTONES.md — uevent",
        "commit": "feat(driver): port uevent parse from day11",
    },
    "2026-09-11/rust/clvm_reloc_verify": {
        "project": "projects/chris-vm",
        "carry": "reloc verify rust",
        "tests": "cargo tests",
        "milestone": "MILESTONES.md — reloc verify",
        "commit": "feat(vm): port reloc verify from day11",
    },
    "2026-09-11/dotnet/pe_import_span": {
        "project": "projects/chris-dotnet-pe",
        "carry": "PE import span",
        "tests": "dotnet test",
        "milestone": "MILESTONES.md — import",
        "commit": "feat(pe): port import span from day11",
    },
    "2026-09-11/graphics/alpha_blend_scanline": {
        "project": "projects/chris-renderer",
        "carry": "alpha blend scanline",
        "tests": "blend tests",
        "milestone": "MILESTONES.md — blend",
        "commit": "feat(renderer): port blend from day11",
    },
    "2026-09-11/redteam/import_name_triage": {
        "project": "projects/chris-binary-toolkit",
        "carry": "import triage",
        "tests": "pytest",
        "milestone": "MILESTONES.md — triage",
        "commit": "feat(toolkit): port import triage from day11",
    },
    "2026-09-11/quantum/phase_kickback": {
        "project": "projects/chris-qsim",
        "carry": "phase kickback",
        "tests": "phase tests",
        "milestone": "MILESTONES.md — phase",
        "commit": "feat(qsim): port phase from day11",
    },
    "2026-09-11/ai/rms_norm": {
        "project": "projects/chris-tensor",
        "carry": "RMSNorm",
        "tests": "rms tests",
        "milestone": "MILESTONES.md — rms",
        "commit": "feat(tensor): port rms from day11",
    },
    "2026-09-11/nodejs/shared_atomics_ring": {
        "project": "projects/chris-node-streaming",
        "carry": "atomics ring",
        "tests": "node test.js",
        "milestone": "MILESTONES.md — ring",
        "commit": "feat(node): port ring from day11",
    },
    "2026-09-11/parsers/ini_rd_lexer": {
        "project": "projects/chris-smart-grep",
        "carry": "INI lexer",
        "tests": "ini tests",
        "milestone": "MILESTONES.md — ini",
        "commit": "feat(parsers): port ini lexer from day11",
    },
    "2026-09-11/agent/tool_barrier_join": {
        "project": "projects/chris-agent-harness",
        "carry": "tool barrier",
        "tests": "pytest",
        "milestone": "MILESTONES.md — barrier",
        "commit": "feat(agent): port barrier from day11",
    },
    "2026-09-11/tooling/coff_sym_name": {
        "project": "projects/chris-binary-toolkit",
        "carry": "COFF sym name asm",
        "tests": "ctest",
        "milestone": "MILESTONES.md — coff",
        "commit": "feat(toolkit): port coff name from day11",
    },

    "2026-09-08/systems/spsc_ring_buffer": {
        "project": "projects/chris-driver-lab",
        "carry": "spsc_ring_buffer from day08 github track",
        "tests": "day08 module tests",
        "milestone": "MILESTONES.md — spsc_ring_buffer",
        "commit": "feat(day08): port spsc_ring_buffer",
    },

    "2026-09-08/architecture/cache_set_sim": {
        "project": "projects/chris-cpu",
        "carry": "cache_set_sim from day08 github track",
        "tests": "day08 module tests",
        "milestone": "MILESTONES.md — cache_set_sim",
        "commit": "feat(day08): port cache_set_sim",
    },

    "2026-09-08/ai/online_softmax": {
        "project": "projects/chris-tensor",
        "carry": "online_softmax from day08 github track",
        "tests": "day08 module tests",
        "milestone": "MILESTONES.md — online_softmax",
        "commit": "feat(day08): port online_softmax",
    },

    "2026-09-08/redteam/wasm_binary_triage": {
        "project": "projects/chris-binary-toolkit",
        "carry": "wasm_binary_triage from day08 github track",
        "tests": "day08 module tests",
        "milestone": "MILESTONES.md — wasm_binary_triage",
        "commit": "feat(day08): port wasm_binary_triage",
    },

    "2026-09-08/parsers/nfa_to_dfa": {
        "project": "projects/chris-regex",
        "carry": "nfa_to_dfa from day08 github track",
        "tests": "day08 module tests",
        "milestone": "MILESTONES.md — nfa_to_dfa",
        "commit": "feat(day08): port nfa_to_dfa",
    },

    "2026-09-08/agent/bm25_code_ranker": {
        "project": "projects/chris-agent-core",
        "carry": "bm25_code_ranker from day08 github track",
        "tests": "day08 module tests",
        "milestone": "MILESTONES.md — bm25_code_ranker",
        "commit": "feat(day08): port bm25_code_ranker",
    },

    "2026-09-08/unix/xargs_lite": {
        "project": "projects/chris-xargs",
        "carry": "xargs_lite from day08 github track",
        "tests": "day08 module tests",
        "milestone": "MILESTONES.md — xargs_lite",
        "commit": "feat(day08): port xargs_lite",
    },

    "2026-09-08/nodejs/worker_transfer": {
        "project": "projects/chris-node-streaming",
        "carry": "worker_transfer from day08 github track",
        "tests": "day08 module tests",
        "milestone": "MILESTONES.md — worker_transfer",
        "commit": "feat(day08): port worker_transfer",
    },

    "2026-09-08/dotnet/gc_allocation_probe": {
        "project": "projects/chris-dotnet-bench",
        "carry": "gc_allocation_probe from day08 github track",
        "tests": "day08 module tests",
        "milestone": "MILESTONES.md — gc_allocation_probe",
        "commit": "feat(day08): port gc_allocation_probe",
    },

}

def module_key(day: str, rel_mod: str) -> str:
    return f"{day}/{rel_mod}"
