"""Map day modules to cumulative projects/ for porting guide."""
from __future__ import annotations

MODULE_PROJECT: dict[str, dict[str, str]] = {
    # Day 01
    "2026-09-03/ai/linear_autograd": {
        "project": "projects/chris-autograd",
        "carry": "gradient ops + training loop (not lab harness)",
        "tests": "gradient/regression tests in project",
        "milestone": "MILESTONES.md — scalar autograd",
        "commit": "feat(autograd): port linear training from day01 lab",
    },
    "2026-09-03/architecture/toy_cpu": {
        "project": "projects/chris-cpu",
        "carry": "fetch/decode/execute core",
        "tests": "unit tests for opcode semantics",
        "milestone": "MILESTONES.md — instruction subset",
        "commit": "feat(cpu): port toy CPU from day01 lab",
    },
    "2026-09-03/assembly/x86_64_abi_sum": {
        "project": "projects/chris-assembly-lab",
        "carry": "System V sum function in assembly",
        "tests": "ABI boundary tests",
        "milestone": "MILESTONES.md — ABI lab",
        "commit": "feat(asm): port x86-64 sum from day01 lab",
    },
    "2026-09-03/blockchain/toy_chain": {
        "project": "projects/chris-chain",
        "carry": "block hash + chain validation",
        "tests": "tamper/PoW tests",
        "milestone": "MILESTONES.md — hash chain",
        "commit": "feat(chain): port toy chain from day01 lab",
    },
    "2026-09-03/boot/legacy_bootsector": {
        "project": "projects/chris-boot",
        "carry": "512-byte boot sector layout",
        "tests": "binary layout tests",
        "milestone": "MILESTONES.md — boot sector",
        "commit": "feat(boot): port legacy bootsector from day01 lab",
    },
    "2026-09-03/graphics/dual_backend_3d": {
        "project": "projects/chris-renderer",
        "carry": "shared 3D core + backend interface",
        "tests": "software vs GL parity tests",
        "milestone": "MILESTONES.md — dual backend",
        "commit": "feat(renderer): port 3D core from day01 lab",
    },
    "2026-09-03/hardware/descriptor_ring": {
        "project": "projects/chris-driver-lab",
        "carry": "descriptor ring submit/complete",
        "tests": "wrap/full/order tests",
        "milestone": "MILESTONES.md — NIC ring sim",
        "commit": "feat(driver): port descriptor ring from day01 lab",
    },
    "2026-09-03/network/http_parser": {
        "project": "projects/chris-http",
        "carry": "incremental HTTP/1.x parser",
        "tests": "fragmentation + negative cases",
        "milestone": "MILESTONES.md — HTTP parser",
        "commit": "feat(http): port incremental parser from day01 lab",
    },
    "2026-09-03/p2p/gossip": {
        "project": "projects/chris-p2p",
        "carry": "gossip dedup + TTL broadcast",
        "tests": "topology/property tests",
        "milestone": "MILESTONES.md — gossip sim",
        "commit": "feat(p2p): port gossip from day01 lab",
    },
    "2026-09-03/redteam/benign_reversing": {
        "project": "projects/chris-binary-toolkit",
        "carry": "strings/YARA-style scanning",
        "tests": "unit tests on fixtures",
        "milestone": "MILESTONES.md — binary toolkit",
        "commit": "feat(toolkit): port reversing helpers from day01 lab",
    },
    "2026-09-03/systems/clvm": {
        "project": "projects/chris-vm",
        "carry": "CLVM loader + stack VM",
        "tests": "integration tests",
        "milestone": "MILESTONES.md — CLVM VM",
        "commit": "feat(vm): port CLVM from day01 lab",
    },
    "2026-09-04/systems/clvm_extended": {
        "project": "projects/chris-vm",
        "carry": "CALL/RET, LOAD/STORE, EQ/LT/JNZ/SWAP/DROP",
        "tests": "add2 + mem_demo + max_loop + negatives",
        "milestone": "MILESTONES.md — Day 04 extended ISA",
        "commit": "feat(vm): extended ISA from day04 clvm_extended",
    },
    "2026-09-07/systems/clvm_js_codegen": {
        "project": "projects/chris-vm",
        "carry": "js2clvm codegen (LET/WHILE/CALL)",
        "tests": "integration_test.py goldens",
        "milestone": "MILESTONES.md — N1 codegen lab",
        "commit": "feat(vm): port js codegen from day07",
    },
    "2026-09-07/systems/clvm_bytecode_verifier": {
        "project": "projects/chris-vm",
        "carry": "verify_clvm stack-effect + branches",
        "tests": "fixtures ok/bad_checksum",
        "milestone": "MILESTONES.md — N2 verifier lab",
        "commit": "feat(vm): port verifier from day07",
    },
    "2026-09-07/systems/clvm_v2_strings": {
        "project": "projects/chris-vm",
        "carry": "FORMAT v2 string pool + PRINTS (experimental)",
        "tests": "hello hi",
        "milestone": "MILESTONES.md — N4 v2 strings",
        "commit": "feat(vm): explore CLVM v2 strings from day07",
    },
    "2026-09-07/linux/hid_keyboard_boot": {
        "project": "projects/chris-driver-lab",
        "carry": "HID boot keyboard decode + input ring",
        "tests": "hid_kbd_test ctest",
        "milestone": "MILESTONES.md — HID input queue",
        "commit": "feat(driver-lab): port hid keyboard boot from day07",
    },
    "2026-09-07/linux/ps2_mouse_input": {
        "project": "projects/chris-driver-lab",
        "carry": "PS/2 mouse packet → relative events",
        "tests": "ps2_mouse_test ctest",
        "milestone": "MILESTONES.md — PS/2 input",
        "commit": "feat(driver-lab): port ps2 mouse from day07",
    },
    "2026-09-07/rust/clvm_v2_verify": {
        "project": "projects/chris-vm",
        "carry": "Rust CLVM v2 parser + stack verify",
        "tests": "cargo test clvm_v2",
        "milestone": "MILESTONES.md — rust verifier v2",
        "commit": "feat(vm): rust clvm v2 verifier from day07",
    },
    "2026-09-07/dotnet/input_event_span": {
        "project": "projects/chris-dotnet-bench",
        "carry": "evdev InputEvent + Span HID/PS2 parsers",
        "tests": "dotnet test InputLab",
        "milestone": "MILESTONES.md — input span parsers",
        "commit": "feat(dotnet-bench): port input event span from day07",
    },
    "2026-09-03/terminal/ansi_parser": {
        "project": "projects/chris-terminal",
        "carry": "ECMA-48/ANSI state machine",
        "tests": "golden/state tests",
        "milestone": "MILESTONES.md — terminal parser",
        "commit": "feat(terminal): port ANSI parser from day01 lab",
    },
    "2026-09-03/tooling/miniobjdump": {
        "project": "projects/chris-disassembler",
        "carry": "ELF/PE inspection + decode subset",
        "tests": "integration tests",
        "milestone": "MILESTONES.md — disassembler",
        "commit": "feat(disasm): port miniobjdump from day01 lab",
    },
    # Day 02
    "2026-09-04/systems/arena_allocator": {
        "project": "projects/chris-arena",
        "carry": "Arena allocate/reset/align",
        "tests": "arena unit tests",
        "milestone": "MILESTONES.md — arena allocator",
        "commit": "feat(arena): port allocator from day02 lab",
    },
    "2026-09-04/ai/tensor_strides": {
        "project": "projects/chris-tensor",
        "carry": "strided tensor views + matmul",
        "tests": "tensor shape tests",
        "milestone": "MILESTONES.md — tensor core",
        "commit": "feat(tensor): port strides from day02 lab",
    },
    "2026-09-04/algorithms/blocked_merge_sort": {
        "project": "projects/chris-algorithms",
        "carry": "blocked merge sort + SortIoStats",
        "tests": "correctness + tile I/O accounting",
        "milestone": "MILESTONES.md — blocked merge sort",
        "commit": "feat(algo): port blocked merge sort from day02 lab",
    },
    "2026-09-04/quantum/statevector_intro": {
        "project": "projects/chris-qsim",
        "carry": "statevector gates",
        "tests": "gate unit tests",
        "milestone": "MILESTONES.md — qsim intro",
        "commit": "feat(qsim): port statevector from day02 lab",
    },
    "2026-09-04/os/graphics_reference": {
        "project": "projects/chris-os",
        "carry": "software compositor",
        "tests": "pixel compositing tests",
        "milestone": "MILESTONES.md — OS graphics ref",
        "commit": "feat(os): port compositor from day02 lab",
    },
    "2026-09-04/debugger/protocol_v1": {
        "project": "projects/chris-debugger",
        "carry": "debugger wire protocol v1",
        "tests": "encode/decode roundtrip",
        "milestone": "MILESTONES.md — protocol v1",
        "commit": "feat(debugger): port protocol from day02 lab",
    },
    "2026-09-04/redteam/elf64_triage": {
        "project": "projects/chris-binary-toolkit",
        "carry": "ELF64 header triage",
        "tests": "elf64_benchmark.py",
        "milestone": "MILESTONES.md — ELF triage",
        "commit": "feat(toolkit): port elf64 triage from day02 lab",
    },
    "2026-09-04/dotnet/csharp_span_arraypool": {
        "project": "projects/chris-dotnet-bench",
        "carry": "Span/ArrayPool patterns",
        "tests": "dotnet benchmarks",
        "milestone": "MILESTONES.md — .NET buffers",
        "commit": "feat(dotnet): port span lab from day02",
    },
    "2026-09-04/dotnet/clr_pe_cli_metadata": {
        "project": "projects/chris-dotnet-pe",
        "carry": "PE/CLI metadata reader",
        "tests": "PE fixture tests",
        "milestone": "MILESTONES.md — PE reader",
        "commit": "feat(pe): port CLR metadata from day02 lab",
    },
    "2026-09-04/nodejs/typescript_stream_backpressure": {
        "project": "projects/chris-node-streaming",
        "carry": "Transform stream + backpressure",
        "tests": "stream unit tests",
        "milestone": "MILESTONES.md — Node streams",
        "commit": "feat(node): port TS streams from day02 lab",
    },
    "2026-09-04/javascript/bytecode_vm_from_scratch": {
        "project": "projects/chris-js",
        "carry": "bytecode VM core",
        "tests": "vm test.js",
        "milestone": "MILESTONES.md — JS VM",
        "commit": "feat(js): port bytecode VM from day02 lab",
    },
    # Day 05
    "2026-09-05/ai/tiled_matmul_cache": {
        "project": "projects/chris-tensor/day03_tiled_matmul",
        "carry": "tiled matmul + bench",
        "tests": "matmul correctness tests",
        "milestone": "day03 tiled matmul milestone",
        "commit": "feat(tensor): port tiled matmul from day05 lab",
    },
    "2026-09-05/dotnet/cil_tiny_decoder": {
        "project": "projects/chris-dotnet-ilvm/day03",
        "carry": "CIL opcode decoder",
        "tests": "dotnet run on fixtures",
        "milestone": "IL decoder milestone",
        "commit": "feat(ilvm): port CIL decoder from day05 lab",
    },
    "2026-09-05/graphics/vulkan_d3d12_resource_states": {
        "project": "projects/chris-gpu-state/day03",
        "carry": "resource state machine + frame graph",
        "tests": "state transition tests",
        "milestone": "GPU state sim milestone",
        "commit": "feat(gpu): port resource states from day05 lab",
    },
    "2026-09-05/javascript/bytecode_branch_vm": {
        "project": "projects/chris-js/day03_branches",
        "carry": "branching bytecode VM",
        "tests": "vm branch tests",
        "milestone": "JS branch VM milestone",
        "commit": "feat(js): port branch VM from day05 lab",
    },
    "2026-09-05/linux/distro_pkg_rootfs": {
        "project": "projects/chris-linux-pkg/day03",
        "carry": "pkg parser + rootfs builder",
        "tests": "test_pkg.py + test_rootfs.sh",
        "milestone": "linux pkg milestone",
        "commit": "feat(linux): port pkg/rootfs from day05 lab",
    },
    "2026-09-05/linux/kernel_module_driver_lab": {
        "project": "projects/chris-linux-module-lab/day03",
        "carry": "device_model userspace + review notes",
        "tests": "test_device_model",
        "milestone": "kmod lab milestone",
        "commit": "feat(kmod): port device model from day05 lab",
    },
    "2026-09-05/linux/pty_ansi_terminal": {
        "project": "projects/chris-linux-terminal/day03_ansi",
        "carry": "ANSI parser for terminal",
        "tests": "test_ansi.py",
        "milestone": "linux terminal milestone",
        "commit": "feat(terminal): port ANSI parser from day05 lab",
    },
    "2026-09-05/nodejs/stream_transform_backpressure": {
        "project": "projects/chris-node-streaming/day03_backpressure",
        "carry": "backpressure demo + transform",
        "tests": "test.js",
        "milestone": "backpressure milestone",
        "commit": "feat(node): port backpressure from day05 lab",
    },
    "2026-09-05/redteam/elf_entry_inspector": {
        "project": "projects/chris-binary-toolkit",
        "carry": "ELF64 entry-point parser",
        "tests": "elf_entry tests",
        "milestone": "ELF entry milestone",
        "commit": "feat(toolkit): port elf entry from day05 lab",
    },
    "2026-09-05/systems/bitmap_page_allocator": {
        "project": "projects/chris-pagealloc/day03",
        "carry": "bitmap page allocator",
        "tests": "page allocator tests",
        "milestone": "pagealloc milestone",
        "commit": "feat(pagealloc): port bitmap allocator from day05 lab",
    },
    "2026-09-07/graphics/artillery_trajectory_2d": {
        "project": "projects/chris-artillery-2d",
        "carry": "2D projectile physics + triple backend",
        "tests": "test_artillery + visual parity",
        "milestone": "artillery 2D milestone",
        "commit": "feat(gfx): port artillery trajectory from day07 lab",
    },
    "2026-09-07/graphics/raster_depth_parity": {
        "project": "projects/chris-renderer/day07-depth",
        "carry": "CPU depth buffer + GL parity",
        "tests": "test_depth",
        "milestone": "depth parity milestone",
        "commit": "feat(renderer): port depth parity from day07 lab",
    },
    "2026-09-07/redteam/hid_report_fuzz": {
        "project": "projects/chris-binary-toolkit",
        "carry": "HID boot report validation + fuzz bounds",
        "tests": "pytest test_hid_fuzz",
        "milestone": "MILESTONES.md — HID fuzz triage",
        "commit": "feat(toolkit): port hid report fuzz from day07",
    },
    "2026-09-07/quantum/measurement_born": {
        "project": "projects/chris-qsim",
        "carry": "Born rule measurement + collapse on 2-qubit statevector",
        "tests": "ctest measure_tests",
        "milestone": "MILESTONES.md — measurement Born lab",
        "commit": "feat(qsim): port measurement born from day07",
    },
    "2026-09-07/ai/input_event_entropy": {
        "project": "projects/chris-tensor",
        "carry": "Shannon + RLE + gzip ratio on InputEvent bytes",
        "tests": "pytest test_input_entropy",
        "milestone": "MILESTONES.md — input event entropy",
        "commit": "feat(tensor): port input event entropy from day07",
    },
    "2026-09-07/nodejs/input_event_transform": {
        "project": "projects/chris-node-streaming",
        "carry": "ESM Transform parsing 24-byte InputEvent records",
        "tests": "node test.js",
        "milestone": "MILESTONES.md — input event transform",
        "commit": "feat(node): port input event transform from day07",
    },
    "2026-09-06/redteam/compressed_blob_triage": {
        "project": "projects/chris-binary-toolkit",
        "carry": "compressed blob magic + bounds triage",
        "tests": "pytest compressed_blob",
        "milestone": "MILESTONES.md — compressed blob triage",
        "commit": "feat(toolkit): port compressed blob triage from day06",
    },
    "2026-09-06/dotnet/span_deflate_buffers": {
        "project": "projects/chris-dotnet-bench",
        "carry": "Span + deflate stored inflate",
        "tests": "dotnet test SpanDeflate",
        "milestone": "MILESTONES.md — span deflate",
        "commit": "feat(dotnet-bench): port span deflate from day06",
    },
    "2026-09-06/rust/rle_byte_codec": {
        "project": "projects/chris-compress",
        "carry": "CHRLE Rust ownership",
        "tests": "cargo test rle",
        "milestone": "MILESTONES.md — rust rle",
        "commit": "feat(compress): port rust rle from day06",
    },
    "2026-09-06/rust/gzip_member_parse": {
        "project": "projects/chris-compress",
        "carry": "gzip member header/trailer parse",
        "tests": "cargo test gzip_member",
        "milestone": "MILESTONES.md — gzip member parse",
        "commit": "feat(compress): port gzip member from day06",
    },
}


def module_key(day: str, rel_mod: str) -> str:
    return f"{day}/{rel_mod}"
