"""Map day modules to cumulative projects/ for porting guide."""
from __future__ import annotations

MODULE_PROJECT: dict[str, dict[str, str]] = {
    # Day 01
    "2026-09-03/ai/linear_autograd": {
        "project": "projects/chris-autograd",
        "carry": "gradient ops + training loop (not lab harness)",
        "tests": "gradient/regression tests in project",
        "milestone": "MILESTONES.md — scalar autograd",
        "commit": "feat(autograd): port linear training from day01 lab",
    },
    "2026-09-03/architecture/toy_cpu": {
        "project": "projects/chris-cpu",
        "carry": "fetch/decode/execute core",
        "tests": "unit tests for opcode semantics",
        "milestone": "MILESTONES.md — instruction subset",
        "commit": "feat(cpu): port toy CPU from day01 lab",
    },
    "2026-09-03/assembly/x86_64_abi_sum": {
        "project": "projects/chris-assembly-lab",
        "carry": "System V sum function in assembly",
        "tests": "ABI boundary tests",
        "milestone": "MILESTONES.md — ABI lab",
        "commit": "feat(asm): port x86-64 sum from day01 lab",
    },
    "2026-09-03/blockchain/toy_chain": {
        "project": "projects/chris-chain",
        "carry": "block hash + chain validation",
        "tests": "tamper/PoW tests",
        "milestone": "MILESTONES.md — hash chain",
        "commit": "feat(chain): port toy chain from day01 lab",
    },
    "2026-09-03/boot/legacy_bootsector": {
        "project": "projects/chris-boot",
        "carry": "512-byte boot sector layout",
        "tests": "binary layout tests",
        "milestone": "MILESTONES.md — boot sector",
        "commit": "feat(boot): port legacy bootsector from day01 lab",
    },
    "2026-09-03/graphics/dual_backend_3d": {
        "project": "projects/chris-renderer",
        "carry": "shared 3D core + backend interface",
        "tests": "software vs GL parity tests",
        "milestone": "MILESTONES.md — dual backend",
        "commit": "feat(renderer): port 3D core from day01 lab",
    },
    "2026-09-03/hardware/descriptor_ring": {
        "project": "projects/chris-driver-lab",
        "carry": "descriptor ring submit/complete",
        "tests": "wrap/full/order tests",
        "milestone": "MILESTONES.md — NIC ring sim",
        "commit": "feat(driver): port descriptor ring from day01 lab",
    },
    "2026-09-03/network/http_parser": {
        "project": "projects/chris-http",
        "carry": "incremental HTTP/1.x parser",
        "tests": "fragmentation + negative cases",
        "milestone": "MILESTONES.md — HTTP parser",
        "commit": "feat(http): port incremental parser from day01 lab",
    },
    "2026-09-03/p2p/gossip": {
        "project": "projects/chris-p2p",
        "carry": "gossip dedup + TTL broadcast",
        "tests": "topology/property tests",
        "milestone": "MILESTONES.md — gossip sim",
        "commit": "feat(p2p): port gossip from day01 lab",
    },
    "2026-09-03/redteam/benign_reversing": {
        "project": "projects/chris-binary-toolkit",
        "carry": "strings/YARA-style scanning",
        "tests": "unit tests on fixtures",
        "milestone": "MILESTONES.md — binary toolkit",
        "commit": "feat(toolkit): port reversing helpers from day01 lab",
    },
    "2026-09-03/systems/clvm": {
        "project": "projects/chris-vm",
        "carry": "CLVM loader + stack VM",
        "tests": "integration tests",
        "milestone": "MILESTONES.md — CLVM VM",
        "commit": "feat(vm): port CLVM from day01 lab",
    },
    "2026-09-03/terminal/ansi_parser": {
        "project": "projects/chris-terminal",
        "carry": "ECMA-48/ANSI state machine",
        "tests": "golden/state tests",
        "milestone": "MILESTONES.md — terminal parser",
        "commit": "feat(terminal): port ANSI parser from day01 lab",
    },
    "2026-09-03/tooling/miniobjdump": {
        "project": "projects/chris-disassembler",
        "carry": "ELF/PE inspection + decode subset",
        "tests": "integration tests",
        "milestone": "MILESTONES.md — disassembler",
        "commit": "feat(disasm): port miniobjdump from day01 lab",
    },
    # Day 02
    "2026-09-04/systems/arena_allocator": {
        "project": "projects/chris-arena",
        "carry": "Arena allocate/reset/align",
        "tests": "arena unit tests",
        "milestone": "MILESTONES.md — arena allocator",
        "commit": "feat(arena): port allocator from day02 lab",
    },
    "2026-09-04/ai/tensor_strides": {
        "project": "projects/chris-tensor",
        "carry": "strided tensor views + matmul",
        "tests": "tensor shape tests",
        "milestone": "MILESTONES.md — tensor core",
        "commit": "feat(tensor): port strides from day02 lab",
    },
    "2026-09-04/algorithms/sorting_research": {
        "project": "projects/chris-algorithms",
        "carry": "instrumented merge/quick sort",
        "tests": "correctness + stability",
        "milestone": "MILESTONES.md — sorting research",
        "commit": "feat(algo): port sorting from day02 lab",
    },
    "2026-09-04/quantum/statevector_intro": {
        "project": "projects/chris-qsim",
        "carry": "statevector gates",
        "tests": "gate unit tests",
        "milestone": "MILESTONES.md — qsim intro",
        "commit": "feat(qsim): port statevector from day02 lab",
    },
    "2026-09-04/os/graphics_reference": {
        "project": "projects/chris-os",
        "carry": "software compositor",
        "tests": "pixel compositing tests",
        "milestone": "MILESTONES.md — OS graphics ref",
        "commit": "feat(os): port compositor from day02 lab",
    },
    "2026-09-04/debugger/protocol_v1": {
        "project": "projects/chris-debugger",
        "carry": "debugger wire protocol v1",
        "tests": "encode/decode roundtrip",
        "milestone": "MILESTONES.md — protocol v1",
        "commit": "feat(debugger): port protocol from day02 lab",
    },
    "2026-09-04/redteam/elf64_triage": {
        "project": "projects/chris-binary-toolkit",
        "carry": "ELF64 header triage",
        "tests": "elf64_benchmark.py",
        "milestone": "MILESTONES.md — ELF triage",
        "commit": "feat(toolkit): port elf64 triage from day02 lab",
    },
    "2026-09-04/dotnet/csharp_span_arraypool": {
        "project": "projects/chris-dotnet-bench",
        "carry": "Span/ArrayPool patterns",
        "tests": "dotnet benchmarks",
        "milestone": "MILESTONES.md — .NET buffers",
        "commit": "feat(dotnet): port span lab from day02",
    },
    "2026-09-04/dotnet/clr_pe_cli_metadata": {
        "project": "projects/chris-dotnet-pe",
        "carry": "PE/CLI metadata reader",
        "tests": "PE fixture tests",
        "milestone": "MILESTONES.md — PE reader",
        "commit": "feat(pe): port CLR metadata from day02 lab",
    },
    "2026-09-04/nodejs/typescript_stream_backpressure": {
        "project": "projects/chris-node-streaming",
        "carry": "Transform stream + backpressure",
        "tests": "stream unit tests",
        "milestone": "MILESTONES.md — Node streams",
        "commit": "feat(node): port TS streams from day02 lab",
    },
    "2026-09-04/javascript/bytecode_vm_from_scratch": {
        "project": "projects/chris-js",
        "carry": "bytecode VM core",
        "tests": "vm test.js",
        "milestone": "MILESTONES.md — JS VM",
        "commit": "feat(js): port bytecode VM from day02 lab",
    },
    # Day 05
    "2026-09-05/ai/tiled_matmul_cache": {
        "project": "projects/chris-tensor/day03_tiled_matmul",
        "carry": "tiled matmul + bench",
        "tests": "matmul correctness tests",
        "milestone": "day03 tiled matmul milestone",
        "commit": "feat(tensor): port tiled matmul from day05 lab",
    },
    "2026-09-05/dotnet/cil_tiny_decoder": {
        "project": "projects/chris-dotnet-ilvm/day03",
        "carry": "CIL opcode decoder",
        "tests": "dotnet run on fixtures",
        "milestone": "IL decoder milestone",
        "commit": "feat(ilvm): port CIL decoder from day05 lab",
    },
    "2026-09-05/graphics/vulkan_d3d12_resource_states": {
        "project": "projects/chris-gpu-state/day03",
        "carry": "resource state machine",
        "tests": "state transition tests",
        "milestone": "GPU state sim milestone",
        "commit": "feat(gpu): port resource states from day05 lab",
    },
    "2026-09-05/javascript/bytecode_branch_vm": {
        "project": "projects/chris-js/day03_branches",
        "carry": "branching bytecode VM",
        "tests": "vm branch tests",
        "milestone": "JS branch VM milestone",
        "commit": "feat(js): port branch VM from day05 lab",
    },
    "2026-09-05/linux/distro_pkg_rootfs": {
        "project": "projects/chris-linux-pkg/day03",
        "carry": "pkg parser + rootfs builder",
        "tests": "test_pkg.py + test_rootfs.sh",
        "milestone": "linux pkg milestone",
        "commit": "feat(linux): port pkg/rootfs from day05 lab",
    },
    "2026-09-05/linux/kernel_module_driver_lab": {
        "project": "projects/chris-linux-module-lab/day03",
        "carry": "device_model userspace + review notes",
        "tests": "test_device_model",
        "milestone": "kmod lab milestone",
        "commit": "feat(kmod): port device model from day05 lab",
    },
    "2026-09-05/linux/pty_ansi_terminal": {
        "project": "projects/chris-linux-terminal/day03_ansi",
        "carry": "ANSI parser for terminal",
        "tests": "test_ansi.py",
        "milestone": "linux terminal milestone",
        "commit": "feat(terminal): port ANSI parser from day05 lab",
    },
    "2026-09-05/nodejs/stream_transform_backpressure": {
        "project": "projects/chris-node-streaming/day03_backpressure",
        "carry": "backpressure demo + transform",
        "tests": "test.js",
        "milestone": "backpressure milestone",
        "commit": "feat(node): port backpressure from day05 lab",
    },
    "2026-09-05/redteam/elf_entry_inspector": {
        "project": "projects/chris-binary-toolkit",
        "carry": "ELF64 entry-point parser",
        "tests": "elf_entry tests",
        "milestone": "ELF entry milestone",
        "commit": "feat(toolkit): port elf entry from day05 lab",
    },
    "2026-09-05/systems/bitmap_page_allocator": {
        "project": "projects/chris-pagealloc/day03",
        "carry": "bitmap page allocator",
        "tests": "page allocator tests",
        "milestone": "pagealloc milestone",
        "commit": "feat(pagealloc): port bitmap allocator from day05 lab",
    },
}


def module_key(day: str, rel_mod: str) -> str:
    return f"{day}/{rel_mod}"
