cmake_minimum_required(VERSION 3.16)
project(wasm_section C)
enable_testing()
if(MSVC)
  enable_language(ASM_MASM)
  add_executable(wasm_section_test test_main.c wasm_section.asm)
else()
  enable_language(ASM)
  add_executable(wasm_section_test test_main.c wasm_section.S)
endif()
add_test(NAME wasm_section_test COMMAND wasm_section_test)
